client_config_backend: settings
client_config:
  client_id: 496706309400-8e1hf2cfac5v8ncdtaiaga3jsv6372c9.apps.googleusercontent.com
  client_secret: SjAMGeq4NpKWRYqziCSwgMHC

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
